name: Build Tester

on:
  push:
    paths:
      - '.github/workflows/build-sample.yml'
  workflow_dispatch:

jobs:
  build-har:
    runs-on: ubuntu-latest
    container:
      image: aliaslsrmrf/clt
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Fetch workflow file
        uses: actions/checkout@v4
      - name: Prepare RNOH build enviroment
        uses: ./.github/actions/prepare-rnoh-env
      - name: Build har
        run: |
          cd packages/react-native-harmony-cli
          pnpm pack
          cd -

          cd packages/react-native-harmony
          pnpm pack
          cd -
      - name: Collect artifact
        id: collect
        run: |
          COMMIT_HASH="$(git rev-parse HEAD | cut -c1-16)"
          mkdir artifacts
          CLI_PATH=$(ls packages/react-native-harmony-cli/react-native-oh-react-native-harmony-cli-*.tgz)
          CLI_NAME=$(basename "$CLI_PATH" .tgz)
          cp CLI_PATH ./artifacts/"$CLI_NAME"-"$COMMIT_HASH".tgz

          HARMONY_PATH=$(ls packages/react-native-harmony/react-native-oh-react-native-harmony-*.tgz)
          HARMONY_NAME=$(basename "$HARMONY_PATH" .tgz)
          cp HARMONY_PATH ./artifacts/"$HARMONY_NAME"-"$COMMIT_HASH".tgz

          cd artifacts
          echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT
          echo "### 📦 Artifact " >> $GITHUB_STEP_SUMMARY
          for f in *; do if [ -f "$f" ]; then echo "$f $((($(stat -c%s "$f") + 512)/1024))K"; fi; done >> $GITHUB_STEP_SUMMARY
      - name: Save built artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.collect.outputs.commit_hash }}
          path: ./artifacts
