name: Build Tester

on:
  push:
    paths:
      - '.github/workflows/build-tester.yml'
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build-tester:
    runs-on: ubuntu-latest
    container:
      image: aliaslsrmrf/clt
    steps:
      - name: Checkout ohos_react_native
        uses: actions/checkout@v4
        with:
          repository: linhandev/ohos_react_native
          ref: 0.77.1-rc.1-ohos
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build tester
        run: |
          pwd
          ls
          env

          sed -i 's|https://gl.swmansion.com/rnoh/react-native-core.git|https://github.com/linhandev/react-native-core.git|g' .gitmodules

          pnpm init-ws
          cd packages/tester/harmony
          ohpm i
          hvigorw --sync -p product=default --analyze=false --parallel --incremental --no-daemon --debug
          hvigorw --mode module -p module=entry@default -p product=default -p buildMode=debug -p requiredDeviceType=phone assembleHap --analyze=false --parallel --incremental --no-daemon --debug
