name: Build llvm

on:
  workflow_dispatch:

jobs:
  build:
    # strategy:
    #   matrix:
    #     os: [macos-13, macos-15]
    # runs-on: ${{ matrix.os }}
    runs-on: macos-13
    steps:
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3.1"
      - name: Check env
        run: |
          set -ex

          uname -m
          xcodebuild -version
          python --version
          python3 --version

      - name: Install dependencies
        run: |
          brew install swig coreutils # git-lfs java wget

      - name: git setup
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Cache source code
        id: cache-source
        uses: actions/cache@v4
        with:
          path: .
          key: repo-source-${{ runner.os }}

      - name: Install repo tool
        if: steps.cache-source.outputs.cache-hit != 'true'
        run: |
          curl https://gitee.com/oschina/repo/raw/fork_flow/repo-py3 > /tmp/repo
          chmod u+x /tmp/repo
          pip install requests

      - name: Repo init and sync (if cache miss)
        if: steps.cache-source.outputs.cache-hit != 'true'
        run: |
          /tmp/repo init -u https://gitee.com/OpenHarmony/manifest.git -b master -m llvm-19.1.7-toolchain.xml
          /tmp/repo sync -c
          /tmp/repo forall -c 'git lfs pull'

      - name: Prepare dependencies
        if: steps.cache-source.outputs.cache-hit != 'true'
        run: |
          ./toolchain/llvm-project/llvm-build/env_prepare.sh

      - name: Build
        run: |
          python3 ./toolchain/llvm-project/llvm-build/build.py --no-build-riscv64 --no-build-mipsel --no-build-loongarch64 --no-build windows

      - name: Upload packages folder
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages
