name: Build Tester

on:
  # push:
  #   paths:
  #     - '.github/workflows/build-tester.yml'
  #     - '.github/actions/prepare-rnoh-env/action.yml'
  workflow_call:
    inputs:
      build_mode:
        description: 'Build mode'
        required: false
        type: string
        default: 'debug'
      js_engine:
        description: 'JS Engine'
        required: false
        type: string
        default: 'jsvm'
    secrets:
      dockerhub_username:
        description: 'DockerHub username'
        required: true
      dockerhub_token:
        description: 'DockerHub token'
        required: true
      signing_config_map:
        description: 'Signing config map'
        required: true

  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Build mode'
        required: false
        type: choice
        options:
          - debug
          - release
        default: 'debug'
      js_engine:
        description: 'JS Engine'
        required: false
        type: choice
        options:
          - jsvm
          - hermes
        default: 'hermes'
  # schedule:
  #   - cron: "0 */6 * * *"

jobs:
  build-tester:
    runs-on: ubuntu-latest
    container:
      image: aliaslsrmrf/clt
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    outputs:
      artifact_name: ${{ steps.collect.outputs.artifact_name }}
    steps:
      - name: Fetch workflow file
        uses: actions/checkout@v4
      - name: Prepare RNOH build enviroment
        uses: ./.github/actions/prepare-rnoh-env
      - name: Build RN
        run: |
          cd packages/tester
          if [ "${{ inputs.js_engine }}" = "jsvm" ]; then
            pnpm run bundle
          else
            npm run bundle:hermes
          fi
      - name: Build native
        run: |
          # add siging config
          npx ts-node workflow_utils/update_signing_config.ts packages/tester/harmony/build-profile.json5 com.rnoh.tester '${{ secrets.SIGNING_CONFIG_MAP }}'
          # uncomment bundle provider
          if [ "${{ inputs.js_engine }}" = "jsvm" ]; then
            npx ts-node workflow_utils/uncomment.ts packages/tester/harmony/entry/src/main/ets/pages/Index.ets "new ResourceJSBundleProvider(this.rnohCoreContext.uiAbilityContext.resourceManager, 'bundle.harmony.js')"
          else
            npx ts-node workflow_utils/uncomment.ts packages/tester/harmony/entry/src/main/ets/pages/Index.ets "new ResourceJSBundleProvider(this.rnohCoreContext.uiAbilityContext.resourceManager, 'hermes_bundle.hbc'),"
          fi

          cd packages/tester/harmony
          ohpm i
          hvigorw --sync -p product=default --analyze=false --parallel --incremental --no-daemon --debug
          hvigorw --mode module -p module=entry@default -p isOhosTest=true -p product=default -p buildMode=${{ inputs.build_mode }} assembleHap --analyze=false --parallel --incremental --no-daemon --debug
          hvigorw --mode module -p module=entry@ohosTest -p isOhosTest=true -p buildMode=test assembleHap --analyze=false --parallel --incremental --no-daemon --debug
      - name: Collect artifact
        id: collect
        run: |
          ARTIFACT_NAME="tester-$(git rev-parse HEAD | cut -c1-16)-${{ inputs.js_engine }}-${{ inputs.build_mode }}"
          mkdir $ARTIFACT_NAME
          cp packages/tester/harmony/entry/build/default/outputs/default/entry-default-signed.hap ./$ARTIFACT_NAME/"$ARTIFACT_NAME".hap
          cp packages/tester/harmony/entry/build/default/outputs/ohosTest/entry-ohosTest-signed.hap ./$ARTIFACT_NAME/"$ARTIFACT_NAME"-test.hap
          
          cd $ARTIFACT_NAME
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          echo "### 📦 Artifact " >> $GITHUB_STEP_SUMMARY
          for f in *; do if [ -f "$f" ]; then echo "$f $((($(stat -c%s "$f") + 512)/1024))K"; fi; done >> $GITHUB_STEP_SUMMARY
      - name: Save built artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.collect.outputs.artifact_name }}
          path: ./${{ steps.collect.outputs.artifact_name }}

  run-ut:
    needs: build-tester
    uses: linhandev/actions/.github/workflows/run-ut.yml@develop
    with:
      artifact_name: ${{ needs.build-tester.outputs.artifact_name }}
