name: Build Samples

on:
  push:
    paths:
      - '.github/workflows/build-sample.yml'
  workflow_dispatch:

jobs:
  build-npm-packages:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.collect.outputs.commit_hash }}
    container:
      image: aliaslsrmrf/clt
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Fetch workflow file
        uses: actions/checkout@v4
      - name: Initialize RNOH
        uses: ./.github/actions/init-rnoh
      - name: Build har
        run: |
          pnpm concurrently \
            --kill-others-on-fail \
            --names "CLI,HARMONY" \
            "cd packages/react-native-harmony-cli && pnpm pack" \
            "cd packages/react-native-harmony && pnpm pack"

      - name: Collect artifact
        id: collect
        run: |
          COMMIT_HASH="$(git rev-parse HEAD | cut -c1-16)"
          mkdir artifacts
          CLI_PATH=$(ls packages/react-native-harmony-cli/react-native-oh-react-native-harmony-cli-*.tgz)
          CLI_NAME=$(basename "$CLI_PATH" .tgz)
          cp $CLI_PATH ./artifacts/"$CLI_NAME"-"$COMMIT_HASH".tgz

          HARMONY_PATH=$(ls packages/react-native-harmony/react-native-oh-react-native-harmony-*.tgz)
          HARMONY_NAME=$(basename "$HARMONY_PATH" .tgz)
          cp $HARMONY_PATH ./artifacts/"$HARMONY_NAME"-"$COMMIT_HASH".tgz

          cd artifacts
          echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT
          echo "### 📦 Artifact " >> $GITHUB_STEP_SUMMARY
          for f in *; do if [ -f "$f" ]; then echo "$f $((($(stat -c%s "$f") + 512)/1024))K"; fi; done >> $GITHUB_STEP_SUMMARY

      - name: Save built artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.collect.outputs.commit_hash }}-npm-packages
          path: ./artifacts

  build-sample:
    runs-on: ubuntu-latest
    needs: build-npm-packages
    strategy:
      matrix:
        sample-name: 
          - sample-basic
    container:
      image: aliaslsrmrf/clt
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-npm-packages.outputs.commit_hash }}-npm-packages
          path: ./downloaded-artifacts
      
      - name: Get artifact paths
        id: paths
        run: |
          CLI_ARTIFACT=$(find ./downloaded-artifacts -name "*react-native-oh-react-native-harmony-cli-*.tgz" -type f)
          HARMONY_ARTIFACT=$(find ./downloaded-artifacts -name "*react-native-oh-react-native-harmony-*.tgz" -type f | grep -v cli)
          
          CLI_ABSOLUTE_PATH=$(realpath "$CLI_ARTIFACT")
          HARMONY_ABSOLUTE_PATH=$(realpath "$HARMONY_ARTIFACT")
          BUILD_SCRIPT_PATH="$GITHUB_WORKSPACE/workflow_utils/sample/build_scripts/${{ matrix.sample-name }}.sh"
          
          echo "Found CLI artifact: $CLI_ABSOLUTE_PATH"
          echo "Found Harmony artifact: $HARMONY_ABSOLUTE_PATH"
          echo "Build script path: $BUILD_SCRIPT_PATH"

          cat #BUILD_SCRIPT_PATH
          
          cd docs/Samples/${{ matrix.sample-name }}
          SIGNING_CONFIG_MAP='${{ secrets.SIGNING_CONFIG_MAP }}'
          source $GITHUB_WORKSPACE/workflow_utils/sample/build_scripts/${{ matrix.sample-name }}.sh
