name: Build Tester

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"


jobs:
  build-tester:
    runs-on: ubuntu-latest
    container:
      image: aliaslsrmrf/clt
    steps:
      - name: Checkout ohos_react_native
        uses: actions/checkout@v4
        with:
          repository: linhandev/ohos_react_native
          ref: 0.77.1-rc.1-ohos
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - name: Mark repo as safe for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build tester
        run: |
          pwd
          ls
          env

          pnpm init-ws
          cd packages/tester/harmony
          ohpm i
          hvigorw --sync -p product=default --analyze=false --parallel --incremental --no-daemon --debug
          hvigorw --mode module -p module=entry@default -p product=default -p buildMode=debug -p requiredDeviceType=phone assembleHap --analyze=false --parallel --incremental --no-daemon --debug
