name: Run ut

on:
  push:
    paths:
      - .github/workflows/run-ut.yml
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      bundle_name:
        required: false
        type: string
        default: "com.rnoh.tester"
concurrency:
  group: run-on-device

jobs:
  test-hap:
    runs-on: self-hosted
    steps:
      - name: Setup Env
        run: |
          echo "PATH=$PATH:~/Desktop/software/command-line-tools/sdk/default/openharmony/toolchains/" >> $GITHUB_ENV
      - name: Test has device
        run: |
          output=$(hdc list targets)
          echo "$output"
          if [[ "$output" == "[Empty]" ]]; then
            echo "No device found, please connect a device and try again."
            exit 1
          fi
      - name: Download HAP artifact
        if: github.event_name == 'workflow_call'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Install HAP
        if: github.event_name == 'workflow_call'
        run: |
          hdc list targets
          cd ${{ inputs.artifact_name }}
          hdc install ${{ inputs.artifact_name }}.hap
          hdc install ${{ inputs.artifact_name }}-test.hap
      - name: Install hap for local debug
        if: github.event_name != 'workflow_call'
        run: |
          hdc install /home/user/Desktop/software/sample.hap
          # fixme: 2 haps
      - name: Run unittest
        run: |
          hdc rport tcp:8081 tcp:8081
          hdc rport tcp:8082 tcp:8082
          hdc rport tcp:8083 tcp:8083

          hdc shell aa test -b ${{ inputs.bundle_name || 'com.rnoh.tester'}} -m entry_test -s unittest OpenHarmonyTestRunner -s class tester -s timeout 60000 | tee test_output.log
          grep -q "Error: [1-9]\|Failure: [1-9]\|Error in" test_output.log && exit 1
          grep -q "Pass: [1-9]" test_output.log || exit 1
