name: Run ut

on:
  # push:
  #   paths:
  #     - .github/workflows/run-ut.yml
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      bundle_name:
        required: false
        type: string
        default: "com.rnoh.tester"
      repeat_test_for:
        required: false
        type: number
        default: 1
concurrency:
  group: run-on-device
  cancel-in-progress: false

jobs:
  test-hap:
    runs-on: self-hosted
    steps:
      - name: Setup Env
        run: |
          echo "PATH=$PATH:~/Desktop/software/command-line-tools/sdk/default/openharmony/toolchains/" >> $GITHUB_ENV
          echo "hap_name=${{ inputs.artifact_name || 'sample'}}" >> $GITHUB_ENV
          echo "bundle_name=${{ inputs.bundle_name || 'com.rnoh.tester'}}" >> $GITHUB_ENV
          echo "repeat_test_for=${{ inputs.repeat_test_for || 1}}" >> $GITHUB_ENV

      - name: Test has device
        run: |
          output=$(hdc list targets)
          if echo "$output" | grep -q 'Empty'; then
            echo "::error::No connected device found. Plz contact the self-hosted runner admin to attach a device."
            exit 1
          fi

      - name: Download HAP artifact
        if: inputs.artifact_name != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.hap_name }}

      - name: Install HAP
        if: inputs.artifact_name != ''
        run: |
          hdc uninstall ${{ env.bundle_name }}
          tree .
          hdc install ${{ env.hap_name }}.hap
          hdc install ${{ env.hap_name }}-test.hap

      - name: Install hap (for testing ci only, skipped when triggered by other workflow)
        if: inputs.artifact_name == ''
        run: |
          hdc uninstall ${{ env.bundle_name }}
          hdc install /home/user/Desktop/software/sample.hap
          hdc install /home/user/Desktop/software/sample-test.hap

      - name: Run unittest
        id: run_unittest
        run: |
          screen_recording_name="${{ env.hap_name }}-$(date +%Y%m%d_%H%M%S).mp4"
          echo $screen_recording_name
          hdc shell aa start -b com.huawei.hmos.screenrecorder -a com.huawei.hmos.screenrecorder.ServiceExtAbility --ps "CustomizedFileName" "$screen_recording_name"
          sleep 2

          hdc rport tcp:8081 tcp:8081
          hdc rport tcp:8082 tcp:8082
          hdc rport tcp:8083 tcp:8083

          successful_runs=0

          for ((i=1; i<=$repeat_test_for; i++)); do            
            # Run test
            hdc shell aa test -b $bundle_name -m entry_test -s unittest OpenHarmonyTestRunner -s class tester -s timeout 120000 | tee test_output_run_$i.log
            
            # Check test result
            test_passed=true
            if grep -q "Error: [1-9]\|Failure: [1-9]\|Error in" test_output_run_$i.log; then
              echo "Test run $i: ❌ Error or Failure found."  >> $GITHUB_STEP_SUMMARY
              test_passed=false
            fi
            if ! grep -q "Pass: [1-9]" test_output_run_$i.log; then
              echo "Test run $i: ❌ No passing tests found."  >> $GITHUB_STEP_SUMMARY
              test_passed=false
            fi

            if [ "$test_passed" = true ]; then
              successful_runs=$((successful_runs + 1))
              echo "✅ Test run $i: PASSED"
            fi

            # Add a small delay between runs if there are multiple runs
            if [ $i -lt $repeat_test_for ]; then
              sleep 5
            fi
          done

          # Generate summary
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "$successful_runs / $repeat_test_for passed, pass rate $((successful_runs * 100 / repeat_test_for))%" >> $GITHUB_STEP_SUMMARY


          # stop record, pull video to runner
          sleep 1
          hdc shell aa start -b com.huawei.hmos.screenrecorder -a com.huawei.hmos.screenrecorder.ServiceExtAbility
          sleep 3

          mkdir ${{ env.hap_name }}-recording
          cd ${{ env.hap_name }}-recording
          video_uri=$(hdc shell mediatool query $screen_recording_name -u | grep "mp4" | tr -d '"')
          video_path=$(hdc shell mediatool recv $video_uri /data/local/tmp/ | grep "mp4")
          hdc file recv $video_path .
          hdc shell rm $video_path
          cd -

          if [ $successful_runs -ne $repeat_test_for ]; then
            exit 1
          fi

      - name: Upload screen recording artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.hap_name }}-recording
          path: ${{ env.hap_name }}-recording
      
      - name: Clean up
        if: always()
        run: |
          # in case recording didn't stop, this wont save the recording
          hdc shell aa force-stop com.huawei.hmos.screenrecorder

          pwd
          ls -lah
          tree
          rm -rf ./*