name: Run ut

on:
  push:
    paths:
      - .github/workflows/run-ut.yml
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      bundle_name:
        required: false
        type: string
        default: "com.rnoh.tester"
concurrency:
  group: run-on-device

jobs:
  test-hap:
    runs-on: self-hosted
    steps:
      - name: Setup Env
        run: |
          echo "PATH=$PATH:~/Desktop/software/command-line-tools/sdk/default/openharmony/toolchains/" >> $GITHUB_ENV
          echo "hap_name=${{ inputs.artifact_name || 'sample'}}" >> $GITHUB_ENV
          echo "bundle_name=${{ inputs.bundle_name || 'com.rnoh.tester'}}" >> $GITHUB_ENV

      - name: Test has device
        run: |
          output=$(hdc list targets)
          if echo "$output" | grep -q 'Empty'; then
            echo "::error::No connected device found. Plz contact the self-hosted runner admin to attach a device."
            exit 1
          fi

      - name: Download HAP artifact
        if: inputs.artifact_name != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.hap_name }}

      - name: Install HAP
        if: inputs.artifact_name != ''
        run: |
          hdc list targets
          hdc uninstall ${{ env.bundle_name }}
          cd ${{ env.hap_name }}
          hdc install ${{ env.hap_name }}.hap
          hdc install ${{ env.hap_name }}-test.hap

      - name: Install hap for local debug
        if: inputs.artifact_name == ''
        run: |
          hdc uninstall ${{ env.bundle_name }}
          hdc install /home/user/Desktop/software/sample.hap
          hdc install /home/user/Desktop/software/sample-test.hap

      - name: Run unittest
        id: run_unittest
        run: |
          screen_recording_name="${{ env.hap_name }}-$(date +%Y%m%d_%H%M%S).mp4"
          echo $screen_recording_name
          hdc shell aa start -b com.huawei.hmos.screenrecorder -a com.huawei.hmos.screenrecorder.ServiceExtAbility --ps "CustomizedFileName" "$screen_recording_name"
          sleep 2

          hdc rport tcp:8081 tcp:8081
          hdc rport tcp:8082 tcp:8082
          hdc rport tcp:8083 tcp:8083

          hdc shell aa test -b ${{ inputs.bundle_name || 'com.rnoh.tester'}} -m entry_test -s unittest OpenHarmonyTestRunner -s class tester -s timeout 30000 | tee test_output.log

          # stop record, pull video to runner
          hdc shell aa start -b com.huawei.hmos.screenrecorder -a com.huawei.hmos.screenrecorder.ServiceExtAbility
          sleep 3

          mkdir ${{ env.hap_name }}-recording
          cd ${{ env.hap_name }}-recording
          video_uri=$(hdc shell mediatool query $screen_recording_name -u | grep "mp4" | tr -d '"')
          video_path=$(hdc shell mediatool recv $video_uri /data/local/tmp/ | grep "mp4")
          hdc file recv $video_path .
          hdc shell rm $video_path
          cd -

          # test result
          grep -q "Error: [1-9]\|Failure: [1-9]\|Error in" test_output.log && exit 1
          grep -q "Pass: [1-9]" test_output.log || exit 1

      - name: Upload screen recording artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.hap_name }}-recording
          path: ${{ env.hap_name }}-recording
      
      - name: Clean up
        if: always()
        run: |
          # in case recording didn't stop, this wont save the recording
          hdc shell aa force-stop com.huawei.hmos.screenrecorder

          pwd
          ls -lah
          tree
          rm -rf ./*