name: Run hap

on:
  push:
    paths:
      - .github/workflows/run-hap.yml
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      bundle_name:
        required: false
        type: string
        default: "com.rnoh.tester"
concurrency:
  group: run-hap

jobs:
  test-hap:
    runs-on: self-hosted
    steps:
      - name: Setup Env
        run: |
          echo "PATH=$PATH:~/Desktop/software/command-line-tools/sdk/default/openharmony/toolchains/" >> $GITHUB_ENV
      - name: Download HAP artifact
        if: github.event_name == 'workflow_call'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Install HAP
        if: github.event_name == 'workflow_call'
        run: |
          hdc list targets
          wget 
          hdc install ${{ inputs.artifact_name }}.hap
      - name: Install hap for local debug
        if: github.event_name != 'workflow_call'
        run: |
          hdc install /home/user/Desktop/software/sample.hap
      - name: Run unittest
        run: |
          hdc shell aa test -b ${{ inputs.bundle_name || 'com.rnoh.tester'}} -m entry_test -s unittest OpenHarmonyTestRunner -s class tester -s timeout 60000
