name: Sync rnc from swm to github

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */6 * * *"

# Ensures that only one mirror task will run at a time.
concurrency:
  group: sync-core

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: "git@gl.swmansion.com:rnoh/react-native-core.git"
          destination-repo: "git@github.com:linhandev/react-native-core.git"
