name: Test All

on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/test-all.yml'

jobs:
  build-tester:
    uses: linhandev/actions/.github/workflows/build-tester.yml@develop
  build-tester-ecosystem:
    uses: linhandev/actions/.github/workflows/build-tester-ecosystem.yml@develop
    secrets:
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
  
