name: Test All

on:
  workflow_dispatch:

jobs:
  build-tester:
    uses: linhandev/actions/.github/workflows/build-tester.yml@develop
  build-tester-eco:
    uses: linhandev/actions/.github/workflows/build-tester-ecosystem.yml@develop
