name: selfhost

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  build-tester:
    runs-on: self-hosted
    steps:
      - run: |
          env
          hdc list targets
          pwd
