name: Test All

on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/test-all.yml'
  schedule:
    - cron: "0 */12 * * *"


jobs:
  build-tester:
    strategy:
      matrix:
        build_mode: [debug, release]
        js_engine: [jsvm, hermes]
    uses: linhandev/actions/.github/workflows/build-tester.yml@develop
    with:
      build_mode: ${{ matrix.build_mode }}
      js_engine: ${{ matrix.js_engine }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      signing_config_map: ${{ secrets.SIGNING_CONFIG_MAP }}
  # build-tester-ecosystem:
  #   uses: linhandev/actions/.github/workflows/build-tester-ecosystem.yml@develop
  #   secrets:
  #       dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
  #       signing_config_map: ${{ secrets.SIGNING_CONFIG_MAP }}